services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"    # Neo4j browser connection port
      - "7687:7687"    # Bolt protocol (for connection with the Python client)
    environment:
      - NEO4J_AUTH=neo4j/strong_password # set the login credentials as username/password
    volumes:
      - neo4j_data:/data # save the neo4j data persistently in a Docker volume, outside the container

  analyzer:
    build:
      context: .
    depends_on:
      - neo4j # wait for neo4j to start before running this (problem is it wait to start, but it should wait for it to finish and only after that start :<)
    environment: # environment varaibles used in my python script
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=strong_password
    volumes:
      - ./plots:/app/plots  # mount host ./plots into container /app/plots

volumes:
  neo4j_data:
