services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"    # Neo4j browser connection port
      - "7687:7687"    # Bolt protocol (for connection with the Python client)
    environment:
      - NEO4J_AUTH=neo4j/strong_password # set the login credentials as username/password
    volumes:
      - neo4j_data:/data # save the neo4j data persistently in a Docker volume, outside the container
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:7474/ || exit 1"] # if neo4j cannot be reached through wget request -> exit 1 (mark as unhealthy)
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  analyzer:
    build:
      context: .
    depends_on:
      neo4j:
        condition: service_healthy
    environment: # environment varaibles used in my python script
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=strong_password
    volumes:
      - ./plots:/app/plots  # mount host ./plots into container /app/plots

volumes:
  neo4j_data:
