services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"    # Neo4j Browser
      - "7687:7687"    # Bolt protocol (for Python connection)
    environment:
      - NEO4J_AUTH=neo4j/strong_password # Set the login credentials username/password
    volumes:
      - neo4j_data:/data # save the neo4j data persistently 

  analyzer:
    build:
      context: .
    depends_on:
      - neo4j # wait for neo4j to start before running this
    environment: # environment varaibles used in my python script
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=strong_password

volumes:
  neo4j_data:
